"""Pure runtime helpers shared by Modal functions and local tests."""

from __future__ import annotations

import re
import shlex
from datetime import UTC, datetime
from pathlib import PurePosixPath
from uuid import uuid4

EGOVERSE_REPOSITORY = "https://github.com/GaTech-RL2/EgoVerse.git"
EGOVERSE_COMMIT = "1d405f5c595b767b7d6ea9d3126d4453a403a6d2"
EGOVERSE_ROOT = PurePosixPath("/opt/egoverse")
VOLUME_ROOT = PurePosixPath("/vol")

_CONFIG_NAME = re.compile(r"^[A-Za-z0-9_.-]+$")
_RUN_ID = re.compile(r"^[0-9]{8}-[0-9]{6}-[0-9a-f]{8}$")
_RESERVED_OVERRIDE_KEYS = {
    "hydra.job.chdir",
    "hydra.run.dir",
    "paths.dataset_dir",
    "paths.root_dir",
}


def new_run_id() -> str:
    """Return a sortable, collision-resistant identifier for a training run."""

    timestamp = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    return f"{timestamp}-{uuid4().hex[:8]}"


def validate_run_id(run_id: str) -> str:
    if not _RUN_ID.fullmatch(run_id):
        raise ValueError("run_id must be generated by new_run_id()")
    return run_id


def parse_override_string(value: str) -> list[str]:
    """Parse shell-style local CLI text into Hydra override tokens."""

    return shlex.split(value) if value.strip() else []


def validate_config_name(config_name: str) -> str:
    if not _CONFIG_NAME.fullmatch(config_name):
        raise ValueError(
            "config_name may contain only letters, numbers, dots, underscores, and dashes"
        )
    return config_name


def validate_overrides(overrides: list[str]) -> list[str]:
    """Validate Hydra assignments while reserving storage-related settings."""

    checked: list[str] = []
    for override in overrides:
        if not isinstance(override, str):
            raise TypeError("every override must be a string")
        if not override or len(override) > 1024:
            raise ValueError("overrides must contain between 1 and 1024 characters")
        if "\x00" in override or "\n" in override or "\r" in override:
            raise ValueError("overrides cannot contain control characters")
        if override.startswith("-") or "=" not in override:
            raise ValueError(f"override must be a Hydra key=value assignment: {override!r}")

        raw_key = override.split("=", 1)[0]
        normalized_key = raw_key.lstrip("+~")
        if normalized_key in _RESERVED_OVERRIDE_KEYS:
            raise ValueError(f"{normalized_key} is managed by the Modal runner")
        checked.append(override)
    return checked


def build_egoverse_command(
    config_name: str,
    overrides: list[str],
    run_id: str,
) -> list[str]:
    """Build the argv used to launch EgoVerse without invoking a shell."""

    config_name = validate_config_name(config_name)
    overrides = validate_overrides(overrides)
    run_id = validate_run_id(run_id)

    command = [
        "python",
        str(EGOVERSE_ROOT / "egomimic" / "trainHydra.py"),
        "--config-name",
        config_name,
        *overrides,
    ]

    override_keys = {
        override.split("=", 1)[0].lstrip("+~") for override in overrides
    }
    if "logger" not in override_keys:
        command.append("logger=debug")

    output_dir = VOLUME_ROOT / "outputs" / run_id
    command.extend(
        [
            f"+paths.root_dir={EGOVERSE_ROOT}",
            f"paths.dataset_dir={VOLUME_ROOT / 'datasets'}",
            f"hydra.run.dir={output_dir}",
            "hydra.job.chdir=True",
        ]
    )
    return command

